=== najoua-elhabti1/PC-Planet/src/main/resources/Data/Categories.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definition of complex types -->

    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:element name="id_category" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="categoriesType">
        <xs:sequence>
            <xs:element ref="category" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition of elements -->

    <xs:element name="category" type="categoryType"/>
    <xs:element name="Categories" type="categoriesType"/>

</xs:schema>

=== najoua-elhabti1/PC-Planet/src/main/resources/Data/Categories.xml
<Categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="Categories.xsd">
    <category>
        <id_category>por</id_category>
        <description>PC_Portable</description>
    </category>
    <category>
        <id_category>bur</id_category>
        <description>PC_Bureau</description>
    </category>
    <category>
        <id_category>tab</id_category>
        <description>Tablette</description>
    </category>
</Categories>
