=== najoua-elhabti1/PC-Planet/src/main/resources/Data/Products.xsd
<!-- products.xsd -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definition of complex types -->


    <xs:complexType name="categoryType">
        <xs:sequence>
            <xs:element name="id_category" type="xs:string"/>
<!--            <xs:element name="description" type="xs:string"/>-->
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="productType">
        <xs:sequence>
            <xs:element name="id_product" type="xs:integer"/>
            <xs:element name="product_name" type="xs:string"/>
            <xs:element name="pr_description" type="xs:string"/>
            <xs:element name="image" type="xs:string"/>
            <xs:element name="price" type="xs:double"/>
            <xs:element name="qte_stock" type="xs:double"/>
            <xs:element name="category" type="categoryType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="productsType">
        <xs:sequence>
            <xs:element ref="product" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Definition of elements -->

    <xs:element name="category" type="categoryType"/>
    <xs:element name="product" type="productType"/>
    <xs:element name="Products" type="productsType"/>

</xs:schema>

=== najoua-elhabti1/PC-Planet/src/main/resources/Data/Products.xml
<?xml version="1.0"?>
<!DOCTYPE Products [
        <!ELEMENT Products (product+)>
        <!ELEMENT product (id_product, product_name, pr_description, image, price, qte_stock, category)>
        <!ELEMENT id_product (#PCDATA)>
        <!ELEMENT product_name (#PCDATA)>
        <!ELEMENT pr_description (#PCDATA)>
        <!ELEMENT image (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT qte_stock (#PCDATA)>
        <!ELEMENT category (id_category)>
        <!ELEMENT id_category (#PCDATA)>
        ]>

<Products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="Products.xsd">
    <product>
        <id_product>1</id_product>
        <product_name>Lenovo ThinkPad A485</product_name>
        <pr_description>CPU : AMD Ryzen™ 5 PRO 2500U  @ 2GHz Up to 3.6GHz
            RAM : 8Go DDR4
            Disque Dur : 256Go SSD
            Ecran : 14″ Full HD
            Radeon™ Vega 8 Graphics 1Go</pr_description>
        <image>/images/001-1.jpg</image>
        <price>2899.00</price>
        <qte_stock>5</qte_stock>
        <category>
            <id_category>por</id_category>
        </category>
    </product>
    <product>
        <id_product>2</id_product>
        <product_name>HP ProBook x360 735 G7 AMD Ryzen 7 Pro 4750u</product_name>
        <pr_description>CPU : AMD® Ryzen™ 7 Pro-4750uU @ 1.7GHz Jusqu`à 4.1GHz
            RAM : 16Go DDR4
            Disque Dur : 512Go NVMe
            Ecran : 13.3″ IPS Full HD Rotation Tactile
            OS : Windows 11 Pro</pr_description>
        <image>/images/hp-x360-435-g7-10.jpg</image>
        <price>6750.00</price>
        <qte_stock>3</qte_stock>
        <category>
            <id_category>por</id_category>
        </category>
    </product>
    <product>
        <id_product>3</id_product>
        <product_name>PC de bureau ABC</product_name>
        <pr_description>Un PC de bureau performant</pr_description>
        <image>images/img_3.png</image>
        <price>900.0</price>
        <qte_stock>30</qte_stock>
        <category>
            <id_category>bur</id_category>
        </category>
    </product>
    <product>
        <id_product>4</id_product>
        <product_name>PC de bureau ABCde</product_name>
        <pr_description>Un PC de bureau performant de </pr_description>
        <image>/images/img_4.png</image>
        <price>900.0</price>
        <qte_stock>20</qte_stock>
        <category>
            <id_category>tab</id_category>
        </category>
    </product>
</Products>
